# Generated by Django 5.1.2 on 2024-10-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formularios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('fecha_fin', models.DateField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('especialidad', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=50)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(default='pendiente', max_length=20)),
            ],
        ),
    ]
