# Generated by Django 5.1.2 on 2024-10-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_formularios_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularios',
            name='segundoapellido',
            field=models.CharField(default='nulo', max_length=20),
        ),
    ]
