# Generated by Django 5.1.2 on 2024-11-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formularios_segundoapellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularios',
            name='rutsupervisor',
            field=models.CharField(default='nulo', max_length=20),
        ),
    ]
