# Generated by Django 5.1.2 on 2024-11-26 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='titulo',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='descripcion',
            new_name='Rangodefecha',
        ),
    ]
