# Generated by Django 5.1.2 on 2024-11-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_titulo_tasks_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='FechaDesde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='FechaHasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
