# Generated by Django 5.1.2 on 2024-11-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('segundoapellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('tipousuario', models.CharField(choices=[('medico', 'Medico'), ('supervisor', 'Supervisor'), ('administrativo', 'Administrativo')], max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('jefeacargo', models.CharField(max_length=50)),
                ('nombresupervisor', models.CharField(default='no tiene', max_length=20)),
                ('apellidosupervisor', models.CharField(default='no tiene', max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
