# Generated by Django 5.1.2 on 2024-11-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usuarios_rutsupervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='emailjefe',
            field=models.EmailField(default='', max_length=35),
        ),
    ]
