# Generated by Django 5.1.2 on 2024-11-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosred', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='if_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
    ]
