# Generated by Django 5.1.2 on 2024-11-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosred', '0005_usuarios_groups_usuarios_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
