# Generated by Django 5.1.2 on 2024-11-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('segundoapellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('tipousuario', models.CharField(choices=[('medico', 'Medico'), ('supervisor', 'Supervisor'), ('administrativo', 'Administrativo')], max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('jefeacargo', models.CharField(max_length=50)),
                ('nommbresupervisor', models.CharField(default='no tiene', max_length=20)),
                ('apellidosupervisor', models.CharField(default='no tiene', max_length=20)),
                ('contraseña', models.CharField(max_length=16)),
            ],
        ),
    ]
